In [12]:
import torch
from torch.nn import functional as F
a = torch.asarray([[1,2,3],[1,2,3],[1,2,3]],dtype=float)
a = a.unsqueeze(0)
a.shape

torch.Size([1, 3, 3])

In [13]:
a

tensor([[[1., 2., 3.],
         [1., 2., 3.],
         [1., 2., 3.]]], dtype=torch.float64)

In [14]:
F.softmax(a, dim = -1)

tensor([[[0.0900, 0.2447, 0.6652],
         [0.0900, 0.2447, 0.6652],
         [0.0900, 0.2447, 0.6652]]], dtype=torch.float64)

In [15]:
F.softmax(a, dim = 1)

tensor([[[0.3333, 0.3333, 0.3333],
         [0.3333, 0.3333, 0.3333],
         [0.3333, 0.3333, 0.3333]]], dtype=torch.float64)